if(DEFINED EMBED_RESOURCE_ENTRY)
    set(resource_file_name "${SPV_FILE}")
    set(source_file_name "${CPP_FILE}")
    set(variable_name "${GLOBAL_VAR}")
    if(EXISTS "${resource_file_name}")
        file(READ "${resource_file_name}" hex_content HEX)
        string(LENGTH "${hex_content}" hex_length)
        math(EXPR trailing_hex_digits "${hex_length} % 8")
        if(hex_length EQUAL 0 OR NOT trailing_hex_digits EQUAL 0)
            message(FATAL_ERROR
                "SPIR-V byte count must be a non-zero multiple of four: ${resource_file_name}")
        endif()

        math(EXPR word_count "${hex_length} / 8")
        math(EXPR last_word_index "${word_count} - 1")
        set(content "")
        foreach(word_index RANGE 0 ${last_word_index})
            math(EXPR word_column "${word_index} % 8")
            if(word_column EQUAL 0)
                string(APPEND content "    ")
            endif()
            math(EXPR byte_offset "${word_index} * 8")
            math(EXPR byte_1_offset "${byte_offset} + 2")
            math(EXPR byte_2_offset "${byte_offset} + 4")
            math(EXPR byte_3_offset "${byte_offset} + 6")
            string(SUBSTRING "${hex_content}" ${byte_offset} 2 byte_0)
            string(SUBSTRING "${hex_content}" ${byte_1_offset} 2 byte_1)
            string(SUBSTRING "${hex_content}" ${byte_2_offset} 2 byte_2)
            string(SUBSTRING "${hex_content}" ${byte_3_offset} 2 byte_3)
            string(APPEND content "0x${byte_3}${byte_2}${byte_1}${byte_0}u")

            if(word_index LESS last_word_index)
                string(APPEND content ",")
            endif()
            math(EXPR words_on_line "(${word_index} + 1) % 8")
            if(words_on_line EQUAL 0 OR word_index EQUAL last_word_index)
                string(APPEND content "\n")
            else()
                string(APPEND content " ")
            endif()
        endforeach()

        set(array_definition
            "inline constexpr std::array<std::uint32_t, ${word_count}> ${variable_name} = {\n${content}};")
        get_filename_component(file_name ${source_file_name} NAME)
        set(source "/**\n * @file ${file_name}\n * @brief 自动生成，请勿手动修改。\n */\n#pragma once\n\n#include <array>\n#include <cstdint>\n\n${array_definition}\n")
        file(WRITE "${source_file_name}" "${source}")
    else()
        message(FATAL_ERROR "Resource file doesn't exist: ${resource_file_name}")
    endif()
    return()
endif()