#pragma once

#include <cassert>
#include <concepts>
#include <cstring>
#include <iostream>
#include <memory>
#include <optional>
#include <ranges>
#include <set>
#include <string>
#include <type_traits>
#include <utility>
#include <cmath>
#include <array>
#include <span>
#include <future>
#include <vector>
#include <unordered_map>
#include <map>
#include <chrono>
#include <algorithm>
#include <functional>
#include <span>
#include <tuple>
#include <mutex>
#include <thread>
#include <cstdio>
#include <iomanip>
#include <sstream>
#include <filesystem>
#include <variant>
