name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y \
              cmake build-essential \
              libx11-dev libxext-dev libxrandr-dev libxinerama-dev \
              libxcursor-dev libxi-dev libwayland-dev libxkbcommon-dev \
              mesa-common-dev libgl1-mesa-dev \
              curl tar \
              libvulkan-dev glslang-tools vulkan-tools
            
            echo "VULKAN_SDK=/usr" >> $GITHUB_ENV

      - name: Cache build files
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('CMakeLists.txt') }}

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure